CSHARP/LoLesports/LoLesports.Web/Models/Jatekos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LoLesports.Web.Models
{
    public class Jatekos
    {
        [Display(Name ="Felhasználónév")]
        [Required]
        public string Felhasznalonev { get; set; }

        [Display(Name = "Vezetéknév")]
        [Required]
        public string Vezeteknev { get; set; }

        [Display(Name = "Keresztnév")]
        [Required]
        public string Keresztnev { get; set; }

        [Display(Name = "Életkor")]
        public Nullable<int> Eletkor { get; set; }

        [Display(Name = "Pozíció")]
        [Required]
        public string Pozicio { get; set; }

        [Display(Name = "Nemzetiség")]
        [Required]
        public string Nemzetiseg { get; set; }

        [Display(Name = "Csapatnév")]
        [Required]
        public string Csapatnev { get; set; }
    }
}

CSHARP/LoLesports/LoLesports.Web/Controllers/JatekosController.cs
using AutoMapper;
using LoLesports.Logic;
using LoLesports.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoLesports.Web.Controllers
{
    public class JatekosController : Controller
    {
        IJatekosLogic jatekosLogic;
        IMapper mapper;
        JatekosokViewModel model;

        public JatekosController()
        {
            jatekosLogic = new JatekosLogic();
            mapper = MapperFactory.CreateMapper();
            model = new JatekosokViewModel();
            model.Editedjatekos = new Jatekos();

            var jatekosok = jatekosLogic.GetAll();
            model.JatekosList = mapper.Map<IList<Data.Jatekos>, List<Models.Jatekos>>(jatekosok);
        }

        private Jatekos GetJatekosModel(string felhasznalonev)
        {
            Data.Jatekos jatekos = jatekosLogic.GetOne(felhasznalonev);
            return mapper.Map<Data.Jatekos, Jatekos>(jatekos);
        }

        // GET: Jatekos
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("JatekosIndex", model);
        }

        // GET: Jatekos/Details/5
        public ActionResult Details(string felhasznalonev)
        {
            return View("JatekosDetails", GetJatekosModel(felhasznalonev));
        }

        public ActionResult Remove(string felhasznalonev)
        {
            TempData["editResult"] = "Delete FAIL";
            if (jatekosLogic.DeleteJatekosElement(felhasznalonev)) TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }

        // GET: Jatekos/Edit/5
        public ActionResult Edit(string felhasznalonev)
        {
            ViewData["editAction"] = "Edit";
            model.Editedjatekos = GetJatekosModel(felhasznalonev);
            return View("JatekosIndex", model);
        }

        // POST: Jatekos/Edit/5
        [HttpPost]
        public ActionResult Edit(Jatekos jatekos, string editAction)
        {
            if (ModelState.IsValid && jatekos != null)
            {
                List<object> jatekoslist = new List<object>();
                jatekoslist.Add(jatekos.Felhasznalonev);
                jatekoslist.Add(jatekos.Vezeteknev);
                jatekoslist.Add(jatekos.Keresztnev);
                jatekoslist.Add(jatekos.Eletkor);
                jatekoslist.Add(jatekos.Pozicio);
                jatekoslist.Add(jatekos.Nemzetiseg);
                jatekoslist.Add(jatekos.Csapatnev);

                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    jatekosLogic.CreateJatekosElement(jatekoslist);
                }
                else
                {
                    if (!jatekosLogic.UpdateJatekosElement(jatekoslist))
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                model.Editedjatekos = jatekos;
                return View("JatekosIndex", model);
            }
        }
    }
}

CSHARP/LoLesports/LoLesports.Web/Views/Jatekos/JatekosDetails.cshtml
@model LoLesports.Web.Models.Jatekos

@{
    ViewBag.Title = "JatekosDetails";
}

<h2>Egy játékos adatai</h2>

@Html.ActionLink("Vissza a listára", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Felhasznalonev)</td>
        <td>@Html.DisplayFor(m => m.Felhasznalonev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Vezeteknev)</td>
        <td>@Html.DisplayFor(m => m.Vezeteknev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Keresztnev)</td>
        <td>@Html.DisplayFor(m => m.Keresztnev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Eletkor)</td>
        <td>@Html.DisplayFor(m => m.Eletkor)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Pozicio)</td>
        <td>@Html.DisplayFor(m => m.Pozicio)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nemzetiseg)</td>
        <td>@Html.DisplayFor(m => m.Nemzetiseg)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Csapatnev)</td>
        <td>@Html.DisplayFor(m => m.Csapatnev)</td>
    </tr>
</table>

CSHARP/LoLesports/LoLesports.Web/Views/Jatekos/JatekosEdit.cshtml
@model LoLesports.Web.Models.Jatekos
@{
    ViewBag.Title = "JatekosEdit";
}

<h2>JatekosEdit</h2>

@using (Html.BeginForm("Edit", "Jatekos"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    <div class="editor-label">@Html.LabelFor(m => m.Felhasznalonev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Felhasznalonev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Vezeteknev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Vezeteknev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Keresztnev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Keresztnev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Eletkor)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Eletkor)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Pozicio)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Pozicio)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Nemzetiseg)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nemzetiseg)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Csapatnev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Csapatnev)</div>

    <input type="submit" value="SEND" />
}

CSHARP/LoLesports/LoLesports.Web/Views/Jatekos/JatekosIndex.cshtml
@model LoLesports.Web.Models.JatekosokViewModel

@{
    ViewBag.Title = "JatekosIndex";
}

<h2>Jatekosok Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@Html.Partial("JatekosEdit", Model.Editedjatekos)

@Html.Partial("JatekosList", Model.JatekosList)

CSHARP/LoLesports/LoLesports.Web/Views/Jatekos/JatekosList.cshtml
@model IEnumerable<LoLesports.Web.Models.Jatekos>
@{
    ViewBag.Title = "JatekosList";
}

<h2>JatekosList</h2>

@if (Model.Count() == 0)
{
<p>Nincs adat az adatbázisban!</p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(m => m.First().Felhasznalonev)</th>
        <th>@Html.DisplayNameFor(m => m.First().Vezeteknev)</th>
        <th>@Html.DisplayNameFor(m => m.First().Keresztnev)</th>
        <th>@Html.DisplayNameFor(m => m.First().Eletkor)</th>
        <th>@Html.DisplayNameFor(m => m.First().Pozicio)</th>
        <th>@Html.DisplayNameFor(m => m.First().Nemzetiseg)</th>
        <th>@Html.DisplayNameFor(m => m.First().Csapatnev)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Edit</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(m => item.Felhasznalonev)</td>
            <td>@Html.DisplayFor(m => item.Vezeteknev)</td>
            <td>@Html.DisplayFor(m => item.Keresztnev)</td>
            <td>@Html.DisplayFor(m => item.Eletkor)</td>
            <td>@Html.DisplayFor(m => item.Pozicio)</td>
            <td>@Html.DisplayFor(m => item.Nemzetiseg)</td>
            <td>@Html.DisplayFor(m => item.Csapatnev)</td>
            <td>@Html.ActionLink("[SHOW]", "Details", new { Felhasznalonev = item.Felhasznalonev })</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { Felhasznalonev = item.Felhasznalonev })</td>
            <td>@Html.ActionLink("[EDIT]", "Edit", new { Felhasznalonev = item.Felhasznalonev })</td>
        </tr>
    }
</table>
}